# Artificial Neural Network

### Importing the libraries

In [24]:
import pandas as pd
import tensorflow as tf
import numpy as np

from sklearn.model_selection import train_test_split

In [25]:
tf.__version__

'2.20.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [26]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [27]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [28]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

## Part 2 - Building the ANN

### Initializing the ANN

In [30]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [31]:
# Dense comes from Density and means "Dichte" -> Deep Learningfddghgh
# units: how many neurons per layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer (will be deep)

In [32]:
# relu means all outputs will be positive
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [33]:
# With regression you don't use a activation function in the output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = None))

## Part 3 - Training the ANN (Artificial Neural Network)

### Compiling the ANN (Backward Propagation)

In [34]:
# optimizer: gradient descent algorithm
# loss: loss function -> calculate difference between Predicted and Actual Value
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 843us/step - loss: 11572.3369
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 394.6592
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 357.4029
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 315.0166
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 270.3482
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 227.5088
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 185.6163
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 148.0197
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 116.3407
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 89.3668  
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 68.7855
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 54.4102
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 44.5983
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 38.7617
Epoch 

### Predicting the Test set results

In [56]:
y_pred = ann.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step


In [69]:
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[427.59 431.23]
 [458.64 460.01]
 [462.17 461.14]
 ...
 [469.35 473.26]
 [436.23 438.  ]
 [455.42 463.28]]
